# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(696, 376)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.dataFrame = QtWidgets.QFrame(self.centralwidget)
        self.dataFrame.setGeometry(QtCore.QRect(10, 50, 151, 211))
        self.dataFrame.setAutoFillBackground(False)
        self.dataFrame.setStyleSheet(".QFrame {background-color: rgb(216, 216, 216); border: 1px solid black}")
        self.dataFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dataFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dataFrame.setObjectName("dataFrame")
        self.lblTitle = QtWidgets.QLabel(self.dataFrame)
        self.lblTitle.setGeometry(QtCore.QRect(30, 0, 92, 19))
        self.lblTitle.setStyleSheet("font-weight: bold; font-size: 12pt")
        self.lblTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTitle.setObjectName("lblTitle")
        self.lblAlt = QtWidgets.QLabel(self.dataFrame)
        self.lblAlt.setGeometry(QtCore.QRect(10, 50, 47, 13))
        self.lblAlt.setStyleSheet("")
        self.lblAlt.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAlt.setObjectName("lblAlt")
        self.lblAltData = QtWidgets.QLabel(self.dataFrame)
        self.lblAltData.setGeometry(QtCore.QRect(70, 50, 47, 13))
        self.lblAltData.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAltData.setObjectName("lblAltData")
        self.lblTimerData = QtWidgets.QLabel(self.dataFrame)
        self.lblTimerData.setGeometry(QtCore.QRect(40, 20, 71, 16))
        self.lblTimerData.setStyleSheet("font-size: 10pt")
        self.lblTimerData.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.lblTimerData.setObjectName("lblTimerData")
        self.lblAltUnit = QtWidgets.QLabel(self.dataFrame)
        self.lblAltUnit.setGeometry(QtCore.QRect(110, 50, 47, 13))
        self.lblAltUnit.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAltUnit.setObjectName("lblAltUnit")
        self.lblAX = QtWidgets.QLabel(self.dataFrame)
        self.lblAX.setGeometry(QtCore.QRect(10, 70, 47, 13))
        self.lblAX.setStyleSheet("")
        self.lblAX.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAX.setObjectName("lblAX")
        self.lblAY = QtWidgets.QLabel(self.dataFrame)
        self.lblAY.setGeometry(QtCore.QRect(10, 90, 47, 13))
        self.lblAY.setStyleSheet("")
        self.lblAY.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAY.setObjectName("lblAY")
        self.lblAZ = QtWidgets.QLabel(self.dataFrame)
        self.lblAZ.setGeometry(QtCore.QRect(10, 110, 47, 13))
        self.lblAZ.setStyleSheet("")
        self.lblAZ.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAZ.setObjectName("lblAZ")
        self.lblAXUnit = QtWidgets.QLabel(self.dataFrame)
        self.lblAXUnit.setGeometry(QtCore.QRect(110, 70, 47, 13))
        self.lblAXUnit.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAXUnit.setObjectName("lblAXUnit")
        self.lblAXData = QtWidgets.QLabel(self.dataFrame)
        self.lblAXData.setGeometry(QtCore.QRect(70, 70, 47, 13))
        self.lblAXData.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAXData.setObjectName("lblAXData")
        self.lblAYUnit = QtWidgets.QLabel(self.dataFrame)
        self.lblAYUnit.setGeometry(QtCore.QRect(110, 90, 47, 13))
        self.lblAYUnit.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAYUnit.setObjectName("lblAYUnit")
        self.lblAYData = QtWidgets.QLabel(self.dataFrame)
        self.lblAYData.setGeometry(QtCore.QRect(70, 90, 47, 13))
        self.lblAYData.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAYData.setObjectName("lblAYData")
        self.lblAZUnit = QtWidgets.QLabel(self.dataFrame)
        self.lblAZUnit.setGeometry(QtCore.QRect(110, 110, 47, 13))
        self.lblAZUnit.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAZUnit.setObjectName("lblAZUnit")
        self.lblAZData = QtWidgets.QLabel(self.dataFrame)
        self.lblAZData.setGeometry(QtCore.QRect(70, 110, 47, 13))
        self.lblAZData.setAlignment(QtCore.Qt.AlignCenter)
        self.lblAZData.setObjectName("lblAZData")
        self.lblGXUnit = QtWidgets.QLabel(self.dataFrame)
        self.lblGXUnit.setGeometry(QtCore.QRect(110, 130, 47, 13))
        self.lblGXUnit.setAlignment(QtCore.Qt.AlignCenter)
        self.lblGXUnit.setObjectName("lblGXUnit")
        self.lblGXData = QtWidgets.QLabel(self.dataFrame)
        self.lblGXData.setGeometry(QtCore.QRect(70, 130, 47, 13))
        self.lblGXData.setAlignment(QtCore.Qt.AlignCenter)
        self.lblGXData.setObjectName("lblGXData")
        self.lblGX = QtWidgets.QLabel(self.dataFrame)
        self.lblGX.setGeometry(QtCore.QRect(10, 130, 47, 13))
        self.lblGX.setStyleSheet("")
        self.lblGX.setAlignment(QtCore.Qt.AlignCenter)
        self.lblGX.setObjectName("lblGX")
        self.lblGY = QtWidgets.QLabel(self.dataFrame)
        self.lblGY.setGeometry(QtCore.QRect(10, 150, 47, 13))
        self.lblGY.setStyleSheet("")
        self.lblGY.setAlignment(QtCore.Qt.AlignCenter)
        self.lblGY.setObjectName("lblGY")
        self.lblGZ = QtWidgets.QLabel(self.dataFrame)
        self.lblGZ.setGeometry(QtCore.QRect(10, 170, 47, 13))
        self.lblGZ.setStyleSheet("")
        self.lblGZ.setAlignment(QtCore.Qt.AlignCenter)
        self.lblGZ.setObjectName("lblGZ")
        self.lblGZUnit = QtWidgets.QLabel(self.dataFrame)
        self.lblGZUnit.setGeometry(QtCore.QRect(110, 170, 47, 13))
        self.lblGZUnit.setAlignment(QtCore.Qt.AlignCenter)
        self.lblGZUnit.setObjectName("lblGZUnit")
        self.lblGYData = QtWidgets.QLabel(self.dataFrame)
        self.lblGYData.setGeometry(QtCore.QRect(70, 150, 47, 13))
        self.lblGYData.setAlignment(QtCore.Qt.AlignCenter)
        self.lblGYData.setObjectName("lblGYData")
        self.lblGYUnit = QtWidgets.QLabel(self.dataFrame)
        self.lblGYUnit.setGeometry(QtCore.QRect(110, 150, 47, 13))
        self.lblGYUnit.setAlignment(QtCore.Qt.AlignCenter)
        self.lblGYUnit.setObjectName("lblGYUnit")
        self.lblGZData = QtWidgets.QLabel(self.dataFrame)
        self.lblGZData.setGeometry(QtCore.QRect(70, 170, 47, 13))
        self.lblGZData.setAlignment(QtCore.Qt.AlignCenter)
        self.lblGZData.setObjectName("lblGZData")
        self.grphAlt = PlotWidget(self.centralwidget)
        self.grphAlt.setGeometry(QtCore.QRect(170, 10, 251, 151))
        self.grphAlt.setStyleSheet("border: 1px solid black")
        self.grphAlt.setObjectName("grphAlt")
        self.grphAlt.setTitle(title="Altitude")
        self.grphAlt.setLabel("left", "Altitude", "m")
        self.grphAlt.setLabel("bottom", "Time", "s")
        self.grphAlt.setBackground('w')
        self.btnStart = QtWidgets.QPushButton(self.centralwidget)
        self.btnStart.setGeometry(QtCore.QRect(10, 10, 71, 31))
        self.btnStart.setObjectName("btnStart")
        self.btnStart_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btnStart_2.setGeometry(QtCore.QRect(90, 10, 71, 31))
        self.btnStart_2.setObjectName("btnStart_2")
        self.grphAcc = PlotWidget(self.centralwidget)
        self.grphAcc.setGeometry(QtCore.QRect(430, 10, 251, 151))
        self.grphAcc.setStyleSheet("border: 1px solid black")
        self.grphAcc.setObjectName("grphAcc")
        self.grphAcc.setTitle(title="Acceleration")
        self.grphAcc.setLabel("left", "Acceleration", "m/s<sup>2</sup>")
        self.grphAcc.setLabel("bottom", "Time", "s")
        self.grphAcc.setBackground('w')
        self.grphGyro = PlotWidget(self.centralwidget)
        self.grphGyro.setGeometry(QtCore.QRect(170, 170, 251, 151))
        self.grphGyro.setStyleSheet("border: 1px solid black")
        self.grphGyro.setObjectName("grphGyro")
        self.grphGyro.setTitle(title="Gyroscope")
        self.grphGyro.setLabel("left", "Angular velocity", "°/s")
        self.grphGyro.setLabel("bottom", "Time", "s")
        self.grphGyro.setBackground('w')
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 696, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Land Computer"))
        self.lblTitle.setText(_translate("MainWindow", "RAW DATA"))
        self.lblAlt.setText(_translate("MainWindow", "Altitude"))
        self.lblAltData.setText(_translate("MainWindow", "0.00"))
        self.lblTimerData.setText(_translate("MainWindow", "0.0"))
        self.lblAltUnit.setText(_translate("MainWindow", "m"))
        self.lblAX.setText(_translate("MainWindow", "aX"))
        self.lblAY.setText(_translate("MainWindow", "aY"))
        self.lblAZ.setText(_translate("MainWindow", "aZ"))
        self.lblAXUnit.setText(_translate("MainWindow", "m/s<sup>2</sup>"))
        self.lblAXData.setText(_translate("MainWindow", "0.00"))
        self.lblAYUnit.setText(_translate("MainWindow", "m/s<sup>2</sup>"))
        self.lblAYData.setText(_translate("MainWindow", "0.00"))
        self.lblAZUnit.setText(_translate("MainWindow", "m/s<sup>2</sup>"))
        self.lblAZData.setText(_translate("MainWindow", "0.00"))
        self.lblGXUnit.setText(_translate("MainWindow", "°/s"))
        self.lblGXData.setText(_translate("MainWindow", "0.00"))
        self.lblGX.setText(_translate("MainWindow", "gX"))
        self.lblGY.setText(_translate("MainWindow", "gY"))
        self.lblGZ.setText(_translate("MainWindow", "gZ"))
        self.lblGZUnit.setText(_translate("MainWindow", "°/s"))
        self.lblGYData.setText(_translate("MainWindow", "0.00"))
        self.lblGYUnit.setText(_translate("MainWindow", "°/s"))
        self.lblGZData.setText(_translate("MainWindow", "0.00"))
        self.btnStart.setText(_translate("MainWindow", "Start"))
        self.btnStart_2.setText(_translate("MainWindow", "Stop"))

from pyqtgraph import PlotWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

